local match_state = require("simulation.match_state")

describe("match_state", function()
	it("new() defaults to 0-0, not over, no winner", function()
		local state = match_state.new()
		assert.are.equal(0, match_state.rounds_for(state, 0))
		assert.are.equal(0, match_state.rounds_for(state, 1))
		assert.is_false(state.match_over)
		assert.are.equal(-1, state.winner_side)
	end)

	it("round_won_by() increments only the winning side's round count", function()
		local state = match_state.new()
		local after = match_state.round_won_by(state, 0)
		assert.are.equal(1, match_state.rounds_for(after, 0))
		assert.are.equal(0, match_state.rounds_for(after, 1))
		assert.is_false(after.match_over)
	end)

	it("best-of-3: the match ends once a side reaches 2 round wins", function()
		local state = match_state.new()
		state = match_state.round_won_by(state, 1)
		state = match_state.round_won_by(state, 1)
		assert.is_true(state.match_over)
		assert.are.equal(1, state.winner_side)
	end)

	it("does not mutate the original state (immutability)", function()
		local state = match_state.new()
		local after = match_state.round_won_by(state, 0)
		assert.are.equal(0, match_state.rounds_for(state, 0))
		assert.are_not.equal(state, after)
	end)
end)
