local rival_encounter_data = require("simulation.rival_encounter_data")

describe("rival_encounter_data", function()
	it("new() defaults to a mook-strength combat encounter with a currency reward", function()
		local r = rival_encounter_data.new()
		assert.is_true(r.is_mook)
		assert.are.equal("combat", r.challenge_type)
		assert.are.equal(0.6, r.mook_hp_multiplier)
		assert.are.equal(100, r.reward_currency)
		assert.is_nil(r.twist)
		assert.is_nil(r.unlock_reward)
	end)

	it("a real rival encounter carries a twist and an unlock reward instead of currency", function()
		local r = rival_encounter_data.new({ is_mook = false, twist = { id = "hazard" }, unlock_reward = { id = "bonus_weapon" } })
		assert.is_false(r.is_mook)
		assert.is_not_nil(r.twist)
		assert.is_not_nil(r.unlock_reward)
	end)

	it("a mook slot can route to a minigame instead of a straight combat", function()
		local r = rival_encounter_data.new({ challenge_type = "breakout" })
		assert.are.equal("breakout", r.challenge_type)
	end)
end)
